Documentation:
  Enabled: false

Style/EmptyLineBetweenDefs:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 17

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'client/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  DisplayStyleGuide: true
  ExtraDetails: true
