language: ruby
sudo: false
services:
  - postgresql
rvm:
  - '2.3.3'
  - '2.2.3'
branches:
  only:
    - master

before_script:
  - "psql -c 'create database rd_test;' -U postgres"
  - "bundle exec rake db:migrate"

addons:
  code_climate:
    repo_token: df5078e3947493295e9c76b9316c150056d50ff213c82452b82c8cfe9ac18a99

after_success:
  - bundle exec codeclimate-test-reporter
