default: &default
  adapter:  postgresql
  host: <%= ENV.fetch('DBHOST') { '127.0.0.1' } %>
  port: <%= ENV.fetch('DBPORT') { 5432 } %>
  encoding: unicode
  pool:     5
  username: <%= ENV.fetch('MYSQL_USERNAME') { 'sampaio' } %>
  password: <%= ENV.fetch('MYSQL_ROOT_PASSWORD') { '' } %>
  template: template0

development:
  <<: *default
  database: <%= ENV.fetch('DBDATABASE') { 'rd_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DBDATABASE') { 'rd_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch('DBDATABASE') { 'rd' } %>
